version: "3"
services:
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    ports:
      - 3306:3306
    # volumes:
    #   - db:/var/lib/mysql
  app:
    depends_on:
      - mysql
    build: .
    restart: on-failure
    ports:
      - 8083:8083
    # environment:
    #   SPRING_APPLICATION_JSON: '{
    #     "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/test?useSSL=false",
    #     "spring.datasource.username" : "root",
    #     "spring.datasource.password" : "root",
    #     "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
    #     "spring.jpa.hibernate.ddl-auto" : "update"
    #                           }'
    # volumes:
    #   - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  db:
